<a href="https://colab.research.google.com/github/ucfilho/Basic_Python/blob/master/Basic_Python_part_002_mar_03_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy commands

In [0]:
import numpy as np

In [2]:
x=np.random.rand()
print(x)
y=np.random.rand(2)
print(y)

0.6389413330562861
[0.03887463 0.1229165 ]


In [3]:
A=np.random.rand(5,6)
print(A)

[[0.08224072 0.43937657 0.71982188 0.42773473 0.34159771 0.85902156]
 [0.23815364 0.09813685 0.35876749 0.89589506 0.12159582 0.67407712]
 [0.77664997 0.37081166 0.78087441 0.01210133 0.58673571 0.79417398]
 [0.88167651 0.432989   0.85142223 0.06658521 0.27552161 0.86726951]
 [0.34075915 0.84300314 0.06037899 0.76756906 0.37508018 0.17461626]]


In [4]:
cols=A.shape[0]
rows=A.shape[1]
print("Number of lines: {} and columns: {}".format(rows,cols))

Number of lines: 6 and columns: 5


In [5]:
x=np.linspace(0,10,5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [6]:
B=np.random.randn(6,5)
print(B)

[[-0.41735542 -1.02627961 -1.04738739  1.65958315  0.37024986]
 [ 0.11996465  0.23174275  0.15387623 -2.12522524 -0.49177911]
 [ 0.873947   -1.39279299 -1.36671865  3.12405808  0.22824888]
 [ 1.20660693 -0.60746293  1.72619148 -0.2378812  -0.95693521]
 [ 0.40957344  1.09861902 -0.45359513  0.69657392  0.80332627]
 [-0.59718403 -0.50955577 -0.79670862  0.3132086  -0.53402239]]


In [7]:
C=np.ones((6,5))
print(C)

y=[]
y=list(map(lambda var: var*2,C))
print(y)

z=[]
z=np.matrix(list(map(lambda var: var*2,C)))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.])]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [8]:
D=np.zeros((6,5))
print(D)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
Max_B=B.max()
Min_B=B.min()
print("the max value of B is {} and the min value of B is {}".format(Max_B,Min_B))


the max value of B is 3.1240580834873373 and the min value of B is -2.125225238784974


In [10]:
rows,cols = np.unravel_index(B.argmax(), B.shape)
print("position of max value: row={} and col={}".format(rows,cols))
print(B[rows,cols])

position of max value: row=2 and col=3
3.1240580834873373


In [11]:
rows,cols = np.unravel_index(B.argmin(), B.shape)
print("position of min value: row={} and col={}".format(rows,cols))
print(B[rows,cols])

position of min value: row=1 and col=3
-2.125225238784974


In [12]:
A=np.random.randn(3,5)
B=np.random.randn(5,3)
C=np.dot(A,B)
print(C)

[[-3.48841638  0.88321456  0.84730135]
 [ 1.24461796  3.05395124 -0.7864049 ]
 [ 2.98083231 -1.34464695  0.54197578]]


In [13]:
D=np.eye(4)
print(D)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
print(D[0,0])
print(D[0][0])
print(D[0,1])
print(D[0][1])

1.0
1.0
0.0
0.0


In [15]:
y=np.arange(1,11)
print(y)
Ind=y>5
print(Ind)
w=y[Ind]
print(w)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
