<a href="https://colab.research.google.com/github/ucfilho/Basic_Python/blob/master/Basic_Python_part_002_mar_03_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy commands

In [0]:
import numpy as np

In [2]:
x=np.random.rand()
print(x)
y=np.random.rand(2)
print(y)

0.06814773930241236
[0.35414217 0.40399193]


In [3]:
A=np.random.rand(5,6)
print(A)

[[0.80105236 0.50100571 0.37714899 0.86714477 0.79620037 0.61462403]
 [0.65436567 0.21983225 0.05605039 0.92636998 0.44491236 0.01416276]
 [0.32494388 0.64052359 0.17810562 0.01732384 0.35475244 0.01688353]
 [0.19608138 0.34793775 0.98189732 0.60161389 0.19154861 0.4375348 ]
 [0.53101621 0.1103393  0.23450335 0.1529202  0.70293951 0.66338861]]


In [4]:
cols=A.shape[0]
rows=A.shape[1]
print("Number of lines: {} and columns: {}".format(rows,cols))

Number of lines: 6 and columns: 5


In [5]:
x=np.linspace(0,10,5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [6]:
B=np.random.randn(6,5)
print(B)

[[-0.86945572  1.27604342 -0.96556365  1.48159443 -0.75415707]
 [ 0.06082195  1.04387078 -1.3360802   0.83251891  1.05962487]
 [ 0.97987407 -0.15110517 -1.32950035 -2.20541896 -0.32223699]
 [-1.42911688  0.55717065 -0.28815439  0.69083038  0.90801168]
 [ 0.36222907  0.23175578  0.29465304  0.80132698 -0.84971411]
 [ 0.04168651 -0.93832303  0.81049601  0.30229785 -2.26836959]]


In [7]:
C=np.ones((6,5))
print(C)

y=[]
y=list(map(lambda var: var*2,C))
print(y)

z=[]
z=np.matrix(list(map(lambda var: var*2,C)))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.])]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [8]:
D=np.zeros((6,5))
print(D)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
Max_B=B.max()
Min_B=B.min()
print("the max value of B is {} and the min value of B is {}".format(Max_B,Min_B))


the max value of B is 1.4815944310980789 and the min value of B is -2.2683695929978778


In [10]:
rows,cols = np.unravel_index(B.argmax(), B.shape)
print("position of max value: row={} and col={}".format(rows,cols))
print(B[rows,cols])

position of max value: row=0 and col=3
1.4815944310980789


In [11]:
rows,cols = np.unravel_index(B.argmin(), B.shape)
print("position of min value: row={} and col={}".format(rows,cols))
print(B[rows,cols])

position of min value: row=5 and col=4
-2.2683695929978778


In [12]:
A=np.random.randn(3,5)
B=np.random.randn(5,3)
C=np.dot(A,B)
print(C)

[[-2.29150296 -2.48616831 -0.02276495]
 [ 0.54678156  1.06686631  1.13379329]
 [-3.26009182 -5.88497088 -3.84694745]]


In [13]:
D=np.eye(4)
print(D)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
