<a href="https://colab.research.google.com/github/ucfilho/Basic_Python/blob/master/Basic_Python_part_002_mar_03_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy commands

In [0]:
import numpy as np

In [2]:
x=np.random.rand()
print(x)
y=np.random.rand(2)
print(y)

0.2595427701797295
[0.5898414  0.28187229]


In [3]:
A=np.random.rand(5,6)
print(A)

[[0.52649649 0.3520605  0.10409862 0.86716864 0.25094482 0.90422051]
 [0.96410274 0.20151709 0.52472178 0.81900949 0.06429826 0.97524312]
 [0.69006957 0.91891106 0.49098123 0.16529726 0.48853664 0.6657887 ]
 [0.218993   0.04317388 0.58733177 0.73623366 0.81470172 0.05683098]
 [0.331629   0.60890975 0.95228498 0.36932177 0.99594181 0.61156476]]


In [4]:
cols=A.shape[0]
rows=A.shape[1]
print("Number of lines: {} and columns: {}".format(rows,cols))

Number of lines: 6 and columns: 5


In [5]:
x=np.linspace(0,10,5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [6]:
B=np.random.randn(6,5)
print(B)

[[-1.23611986 -0.12671752 -0.91993528  0.16668345  0.57672137]
 [ 1.62209004  1.02459583  0.33566351 -1.00694137 -0.29557625]
 [ 0.22431765 -0.5657904  -0.35732958 -0.83198112 -1.03282253]
 [ 0.11240241  0.29699455 -0.46178876 -0.50759861  2.10485289]
 [-0.38997467 -0.99684508  2.81659283  1.46817749  0.08754799]
 [-1.22332016 -0.68948351  1.28013043  0.10940051  1.38416994]]


In [16]:
C=np.ones((6,5))
print(C)

y=[]
y=list(map(lambda var: var*2,C))
print(y)

z=[]
z=np.matrix(list(map(lambda var: var*2,C)))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.])]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [8]:
D=np.zeros((6,5))
print(D)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
Max_B=B.max()
Min_B=B.min()
print("the max value of B is {} and the min value of B is {}".format(Max_B,Min_B))


the max value of B is 2.816592832419775 and the min value of B is -1.236119863279152


In [10]:
rows,cols = np.unravel_index(B.argmax(), B.shape)
print("position of max value: row={} and col={}".format(rows,cols))
print(B[rows,cols])

position of max value: row=4 and col=2
2.816592832419775


In [11]:
rows,cols = np.unravel_index(B.argmin(), B.shape)
print("position of min value: row={} and col={}".format(rows,cols))
print(B[rows,cols])

position of min value: row=0 and col=0
-1.236119863279152


In [12]:
A=np.random.randn(3,5)
B=np.random.randn(5,3)
C=np.dot(A,B)
print(C)

[[ 1.40817841 -0.76165624  0.81026699]
 [ 3.20706704  1.68071377  0.36713843]
 [ 0.84565869  1.88128888 -0.55801302]]


In [13]:
D=np.eye(4)
print(D)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
