<a href="https://colab.research.google.com/github/ucfilho/Basic_Python/blob/master/Basic_Python_part_002_mar_03_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy commands

In [0]:
import numpy as np

In [2]:
x=np.random.rand()
print(x)
y=np.random.rand(2)
print(y)

0.8009931475790486
[0.42042719 0.8319198 ]


In [3]:
A=np.random.rand(5,6)
print(A)

[[0.44832128 0.32311787 0.22698798 0.49392895 0.74538962 0.86377896]
 [0.09848535 0.04977361 0.96664155 0.28332292 0.03452667 0.08716115]
 [0.99664761 0.88895063 0.05108025 0.67984402 0.78557477 0.24198948]
 [0.82553845 0.59486884 0.38094439 0.43707594 0.64010532 0.51568199]
 [0.48441954 0.61626558 0.66727934 0.0971573  0.79844931 0.93195808]]


In [4]:
cols=A.shape[0]
rows=A.shape[1]
print("Number of lines: {} and columns: {}".format(rows,cols))

Number of lines: 6 and columns: 5


In [5]:
x=np.linspace(0,10,5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [6]:
B=np.random.randn(6,5)
print(B)

[[-0.21075521  0.65967291 -0.41967142  1.72045016  0.95130828]
 [ 0.03542991  0.24166412 -1.18527951  0.55412833 -0.44008259]
 [-0.41096932  0.57766915  1.73691037 -0.27664591  0.08797728]
 [ 2.05073753 -1.18176658 -0.61246392 -0.35278548  1.15177416]
 [ 0.2746107   1.34397768 -0.09161807 -0.02647858 -1.08145858]
 [-0.22990572  0.25571654 -0.06923961 -0.85991896 -0.05252265]]


In [7]:
C=np.ones((6,5))
print(C)

y=[]
y=list(map(lambda var: var*2,C))
print(y)

z=[]
z=np.matrix(list(map(lambda var: var*2,C)))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.])]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [8]:
D=np.zeros((6,5))
print(D)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
Max_B=B.max()
Min_B=B.min()
print("the max value of B is {} and the min value of B is {}".format(Max_B,Min_B))


the max value of B is 2.0507375346634085 and the min value of B is -1.1852795119033015


In [10]:
rows,cols = np.unravel_index(B.argmax(), B.shape)
print("position of max value: row={} and col={}".format(rows,cols))
print(B[rows,cols])

position of max value: row=3 and col=0
2.0507375346634085


In [11]:
rows,cols = np.unravel_index(B.argmin(), B.shape)
print("position of min value: row={} and col={}".format(rows,cols))
print(B[rows,cols])

position of min value: row=1 and col=2
-1.1852795119033015


In [12]:
A=np.random.randn(3,5)
B=np.random.randn(5,3)
C=np.dot(A,B)
print(C)

[[ 1.57624953 -1.5244432  -0.67336194]
 [ 1.67691718 -0.05782728 -1.07162197]
 [-2.05355173  1.27332876  1.56568097]]


In [13]:
D=np.eye(4)
print(D)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
print(D[0,0])
print(D[0][0])
print(D[0,1])
print(D[0][1])

1.0
1.0
0.0
0.0


In [15]:
y=np.arange(1,11)
print(y)
Ind=y>5
print(Ind)
w=y[Ind]
print(w)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [16]:
print(y[y>5])

[ 6  7  8  9 10]
