<a href="https://colab.research.google.com/github/ucfilho/Basic_Python/blob/master/Basic_Python_part_002_mar_03_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy commands

In [0]:
import numpy as np

In [2]:
x=np.random.rand()
print(x)
y=np.random.rand(2)
print(y)

0.5683986955894915
[0.36140426 0.53408295]


In [3]:
A=np.random.rand(5,6)
print(A)

[[0.07169431 0.91149144 0.6969841  0.31056744 0.71171396 0.34267027]
 [0.56033129 0.41931908 0.23945405 0.63176301 0.75529869 0.41860781]
 [0.40904018 0.98932037 0.22261632 0.45899277 0.7584654  0.28808087]
 [0.78346734 0.56139595 0.87662698 0.21903135 0.85173956 0.50668322]
 [0.48616196 0.46999763 0.64139446 0.72492065 0.88362989 0.65762444]]


In [4]:
cols=A.shape[0]
rows=A.shape[1]
print("Number of lines: {} and columns: {}".format(rows,cols))

Number of lines: 6 and columns: 5


In [5]:
x=np.linspace(0,10,5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [6]:
B=np.random.randn(6,5)
print(B)

[[ 0.83881696  0.42956051  0.14886312  0.61186053 -0.50739329]
 [-0.28758073 -0.63408868  0.21075768 -0.58805548  0.87795688]
 [ 0.69995659  1.39441978 -1.72662123  2.21067538  2.15827795]
 [-0.45317663  0.53078019  0.08111529 -0.47378699  0.84310755]
 [ 2.00254683  0.55566248 -0.00700129 -0.88580095 -0.49992633]
 [-0.93002298 -1.28942626  0.29193278 -0.03159594 -0.29738566]]


In [7]:
C=np.ones((6,5))
print(C)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
D=np.zeros((6,5))
print(D)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
Max_B=B.max()
Min_B=B.min()
print("the max value of B is {} and the min value of B is {}".format(Max_B,Min_B))


the max value of B is 2.2106753767090837 and the min value of B is -1.7266212337361868


In [10]:
rows,cols = np.unravel_index(B.argmax(), B.shape)
print("position of max value: row={} and col={}".format(rows,cols))
print(B[rows,cols])

position of max value: row=2 and col=3
2.2106753767090837


In [11]:
rows,cols = np.unravel_index(B.argmin(), B.shape)
print("position of min value: row={} and col={}".format(rows,cols))
print(B[rows,cols])

position of min value: row=2 and col=2
-1.7266212337361868


In [12]:
A=np.random.randn(3,5)
B=np.random.randn(5,3)
C=np.dot(A,B)
print(C)

[[ 0.05641792 -2.36756861  2.35687948]
 [ 2.04214246 -0.70148584 -2.43786757]
 [ 0.7552821  -1.65291144 -4.33261227]]


In [13]:
D=np.eye(4)
print(D)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
